export const Hamburger = ({ className }: any) => (
  <svg
    className={className}
    viewBox="0 0 33 26"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <line
      x1="2"
      y1="2"
      x2="31"
      y2="2"
      stroke="#C1FD35"
      strokeWidth="4"
      strokeLinecap="round"
    />
    <line
      x1="2"
      y1="13"
      x2="31"
      y2="13"
      stroke="#C1FD35"
      strokeWidth="4"
      strokeLinecap="round"
    />
    <line
      x1="2"
      y1="24"
      x2="31"
      y2="24"
      stroke="#C1FD35"
      strokeWidth="4"
      strokeLinecap="round"
    />
  </svg>
);
